apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-config
  namespace: dev
data:
  NODE_ENV: "development"
  GATEWAY_PORT: "4000"
  AUTH_SERVICE_PORT: "4003"
  USER_SERVICE_PORT: "4001"
  CHAT_SERVICE_PORT: "4002"
  JWT_EXPIRES_IN: "1d"
  JWT_REFRESH_EXPIRES_IN: "30d"
  SERVICE_NAME: "microservices-dev"