apiVersion: v1
kind: Secret
metadata:
  name: dev-secrets
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: "dev_jwt_secret_key_here_32_chars_minimum"
  JWT_REFRESH_SECRET: "dev_refresh_secret_key_here_32_chars_min"
  INTERNAL_API_TOKEN: "dev_internal_api_token_here_secure_key"
  AUTH_DB_URL: "mysql://auth_user:auth_pass@host.docker.internal:3301/auth_service"
  USER_DB_URL: "postgres://user_user:user_pass@host.docker.internal:5431/user_service"
  MONGO_URL: "mongodb://root:dev_pass@host.docker.internal:27016/chat_service?authSource=admin"
  REDIS_URL: "redis://host.docker.internal:6378"
  RABBITMQ_URL: "amqp://guest:guest@host.docker.internal:25672"