apiVersion: v1
kind: Secret
metadata:
  name: dev-secrets
  namespace: dev
type: Opaque
stringData:
  JWT_SECRET: "MSlob3mPkGd7XAug0P3NGcDR8AUH0vLdQtQry0/deXY="
  JWT_REFRESH_SECRET: "C41f1bhSd+GC1JgLgRn9ZK7NkX9wxCUHR5pstvfPaaw="
  INTERNAL_API_TOKEN: "xVaPwRGJEUbY09mbtIm8krTxXA2jgCtYY5FMMFWUqoo="
  AUTH_DB_URL: "mysql://chatapp_auth_user:chatapp_auth_password@172.19.0.1:18006/chatapp_auth_service"
  USER_DB_URL: "postgres://chatapp_user:chatapp_password@172.19.0.1:18005/chatapp_user_service"
  MONGO_URL: "mongodb://root:password@172.19.0.1:18004/chatapp_chat_service?authSource=admin"
  REDIS_URL: "redis://172.19.0.1:18003"
  RABBITMQ_URL: "amqp://guest:guest@172.19.0.1:18001"