apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: staging
  labels:
    app: chat-service
spec:
  selector:
    app: chat-service
  ports:
  - port: 4002
    targetPort: 4002
    protocol: TCP
  type: ClusterIP
